### ISSUE TITLE
Styling with styled-components

### ISSUE THREAD

**Issue by dmt-13** [fridays/next-routes#107]
Hi. I'm trying to use next-routes together with styled-components. Let's say my component with link looks like this:

```
const StyledLink = styled.a`
  ...
`;

...

<Link route="mainPage">
  <StyledLink>Main page</StyledLink>
</Link>
```

In this case there are no `href` on the `a` tag. But if instead of StyledLink I use `<a className="my-link">Main page</a>`, it works perfectly. Do you have any ideas how I can solve it? Thanks in advance!

**Comment by andreaskeller** [comment]
@dmt-13 you can use the `passHref` property https://github.com/zeit/next.js/issues/1942

**Comment by dmt-13** [comment]
Awesome, thanks a lot! Sorry for opening this issue, didn't know about that property.
