### ISSUE TITLE
Update deps and peer deps for React v16

### ISSUE THREAD

**Issue by jaydenseric** [fridays/next-routes#108]
Dependencies, but more importantly peer dependencies for `react` and `react-dom` need to be updated for React v16:

<img width="1027" alt="screen shot 2017-10-04 at 2 29 50 pm" src="https://user-images.githubusercontent.com/1754873/31158862-8a0e3bd4-a910-11e7-9fc6-dfe383a8474e.png">

**Comment by fridays** [comment]
Updated in version 1.1.0
