### ISSUE TITLE
add locale to url

### ISSUE THREAD

**Issue by apapacy** [fridays/next-routes#110]
Now I can write
```
routes
.add('index', '/:lang(ru|en)?', 'index')
.add('about', '/:lang(ru|en)?/about', 'about')
...
```

It is possible to release?
```
routes
.add('i18n', '/:lang(ru|en)?/:path?', ':path');
````

 Im try to add custom handler but it work only on server
````
function customHandler(args) {
  const {req, res, route, query} = args;
  const path = query.path ? query.path : '';
  app.render(req, res, `/${path}`, query);
}
````

Is the way to customize on client?

**Comment by fridays** [comment]
Not yet, but it’s a good idea! We could make the page parameter optionally accept a function, that receives the paramus and returns the page

**Comment by fridays** [comment]
If anyone wants to look into this right away, changes need to be done [here](https://github.com/fridays/next-routes/blob/944397850cd353fe5fb62f460ecef45ee6543cce/src/index.js#L125) and [here](https://github.com/fridays/next-routes/blob/944397850cd353fe5fb62f460ecef45ee6543cce/src/index.js#L148)

**Comment by samjbmason** [comment]
I would love this funcitonality it looks exactly what I need

**Comment by petertulala** [comment]
Any update on this?
