### ISSUE TITLE
Router refresh problem

### ISSUE THREAD

**Issue by mksglu** [fridays/next-routes#113]
Hi,

I use this package with Router.
`    Router.pushRoute('user', {slug: 'hello-world'})
`
But when I refresh the page, the "pathname" is corrupted. And "This page could not be found." gives a mistake.
Please help.

Thanks.

**Comment by fridays** [comment]
How do you start the app? It sounds like the custom server could be missing, that is needed to resolve urls server-side.

**Comment by mkoseoglu** [comment]
Hi @fridays, Is there a source for that? I'm using Next JS to avoid dealing with the private server. It's ridiculous!

**Comment by fridays** [comment]
Please check the readme at “On the server”. It’s very easy, a single file is needed and next.js will behave exactly the same
