### ISSUE TITLE
Question: Is it possible to generate routes dynamically from database?

### ISSUE THREAD

**Issue by kunokdev** [fridays/next-routes#118]
Basically I am building small CMS and I am wondering if it would be possible to generate routes (ones inside `routes.js`) from database.

**Comment by fridays** [comment]
Hi @kunokdev I recommend you use a catchall route for this, like so:

```js
routes.add('cmspage', '/:pageslug')
```

Then in getInitialProps you can use `query.pageslug` to load the contents from the cms database.

**Comment by kunokdev** [comment]
Thanks, this will do!
