### ISSUE TITLE
handle query strings

### ISSUE THREAD

**Issue by philipheinser** [fridays/next-routes#12]
how would i handle a route like this `domain.com/search?q=foo`. Creating a link `<Link route="search" params={{ q: search }}>` does the right think when clicked but the adressbar only shows `domain.com/search`.

**Comment by fridays** [comment]
Good question! Currently this is not possible. We could change it so that any parameters that are not part of the route definition would be added as query string to the decorated URL. Would that be a good solution?

**Comment by fridays** [comment]
It works like this now, please update to 1.0.20
