### ISSUE TITLE
Next-Routes Hooks

### ISSUE THREAD

**Issue by ed-zm** [fridays/next-routes#125]
Is there any hook in next-routes like in react-router? e.g: `onEnter` hook of react-router. I want to set my authentication/permission but didn't find anything similar in the docs. Thanks in advance

**Comment by fridays** [comment]
Please have a look at Next.js Router Events https://github.com/zeit/next.js/blob/canary/readme.md#router-events

Async things can be done in getInitialProps.

Hope it helps!
