### ISSUE TITLE
Imperative API of prefetch doesn't work

### ISSUE THREAD

**Issue by mocheng** [fridays/next-routes#126]
When prefetch with imperative API like this
```
  routes.getRouter().prefetch('/foo')}
```
It is expected to prefetch javascript URL in given `foo` page.  However, it just directly prefetch-es `/foo`. I suppose it should be able to detects which javascript URL without parsing `/foo` page HTML.

**Comment by fridays** [comment]
Use `routes.Router` to get the Router instance.

`getRouter` is used only internally to wrap the original Router

**Comment by rizkiandrianto** [comment]
@fridays Still not working even with `prefetchRoute()` too 🤔

**Comment by TheBnl** [comment]
I've tried to get the `prefetchRoute()` method to work as well as following.
```js
// pattern with params
const Component = await Router.prefetchRoute('/:slug', { slug: 'slug' });

// name with params
const Component = await Router.prefetchRoute('name', { slug: 'slug' });

// final route
const Component = await Router.prefetchRoute('/slug');
```
But all without success.
Any help or documentation would be much appreciated!
