### ISSUE TITLE
Change target page depending on server/client rendered?

### ISSUE THREAD

**Issue by howells** [fridays/next-routes#129]
Hi! I'm really struggling to wrap my head around how I can conditionally config my routes depending on whether they are rendered on the server or client.

Given these two routes:

````
routes.add('knowledge', '/knowledge', 'knowledge')
routes.add('article', '/knowledge/:id-:slug', 'article')
````

On the client side, I want the article to open in an overlay but have the URL updated appropriately, so I'd like the target page to be 'knowledge', same as the index of articles. If the URL is accessed directly, I'd like the server to render the knowledge page.

Any ideas of how I can achieve this?

**Comment by fridays** [comment]
There is an example app [nextgram](https://github.com/now-examples/nextgram) that does something similar, maybe that helps?

**Comment by howells** [comment]
@fridays ah! Perfect, many thanks

**Comment by joncursi** [comment]
@fridays can you clarify how to do this with `next-routes`? Particularly this line:

https://github.com/now-examples/nextgram/blob/master/pages/index.js#L40

Seems like the first string is saying "let's stay on the same route and add in this query param", and the second string is saying "let's act like we're going to navigate to this URL, but don't actually navigate. let's just change the URL to look like this."

Not sure how to mimic this with `Router.pushRoute(...)`

**Comment by joncursi** [comment]
@howells were you by chance able to figure this one out?

**Comment by howells** [comment]
@joncursi afraid not!
