### ISSUE TITLE
Support shallow rendering

### ISSUE THREAD

**Issue by ccachor** [fridays/next-routes#13]
Is it possible to support shallow rendering to skip rendering getInitialProps? Example: I'd like to use link/router to push a query string to a component that displays a modal based on the query string. Trying to figure out how this can be done without rendering the profile on the server again.

**Comment by fridays** [comment]
Can you share some example code? It sounds like it's more related to next itself. Maybe the nextgram example can help: https://github.com/zeit/nextgram

**Comment by fridays** [comment]
This is now possible thanks to @HaNdTriX - please update to version 1.0.21
