### ISSUE TITLE
Performance: use .some() instead of .reduce()?

### ISSUE THREAD

**Issue by oliviertassinari** [fridays/next-routes#131]
I don't think that we need to loop through all the registered routes:
https://github.com/fridays/next-routes/blob/193f2a38605b03895f6bf9c23c65f72c0338d5c8/src/index.js#L51

**Comment by fridays** [comment]
You're right we could return earlier when a route was found. We used `.find` in the past but people had [problems in IE](https://github.com/fridays/next-routes/issues/27). Maybe a `for` loop with early return would be best
