### ISSUE TITLE
routes.ts is not a module. How to fix this message on typescript?

### ISSUE THREAD

**Issue by johhansantana** [fridays/next-routes#133]
<img width="252" alt="image" src="https://user-images.githubusercontent.com/9933887/35882385-67369956-0b5a-11e8-93f5-1a5394424587.png">

I'm using typescript with nextjs but this error shows up. The library works though.

**Comment by centinel3** [comment]
+1 

Cannot find module './routes'

and on the client when using <Link> : [ts] Module '"/Users/chriscampbell/Desktop/ef prototype/routes"' has no exported member 'Link'.

**Comment by disintegrator** [comment]
I just opened #153 to get typings included in this project :)

You will need to rewrite your code like so:

```js
import routes from '../routes';

const { Link, Route } = routes;
```

Since `routes` is an instance of class Routes ([see here](https://github.com/fridays/next-routes/blob/master/src/index.js#L9)), its members don't get exported as module exports. It's possible to destructure in vanilla JS but TypeScript is stricter about modules.

**Comment by fridays** [comment]
Thanks, it's merged now.

**Comment by ryandrewjohnson** [comment]
I'm using `1.4.2` and still getting the `has no exported member 'Link'` error from TypeScript when trying to import `Link`.

```javascript
import { Link } from '../../server/routes';
```
Was this actually fixed of do I need to use @disintegrator's workaround still?

**Comment by dr-martin** [comment]
> I'm using `1.4.2` and still getting the `has no exported member 'Link'` error from TypeScript when trying to import `Link`.
> 
> ```js
> import { Link } from '../../server/routes';
> ```
> 
> Was this actually fixed of do I need to use @disintegrator's workaround still?

I'm trying to do this with version `1.4.2`, and i confirm is still needed the solution of @disintegrator.

**Comment by olivererdmann** [comment]
> I'm using `1.4.2` and still getting the `has no exported member 'Link'` error from TypeScript when trying to import `Link`.
> 
> ```js
> import { Link } from '../../server/routes';
> ```

I was getting the same error, but was able to fix it by providing additional JSDoc annotations in `routes.js`. This helps TS to figure out the exported types, based on the type-definitions provided by `next-routes`. 

```js
// routes.js

/**
 * @typedef { import("next-routes").Registry } Registry}
 */
const routes = require('next-routes');

/**
 * @type {Registry}
 */
module.exports = routes()
    .add('/:slug', 'page');
```

The import-syntax is specific to TypeScript and described here in detail: https://github.com/Microsoft/TypeScript/wiki/JSDoc-support-in-JavaScript#import-types
