### ISSUE TITLE
Does not work on heroku

### ISSUE THREAD

**Issue by developer239** [fridays/next-routes#136]
Localhost production and development works fine though.

This is my `server.js`:
```
const express = require('express')
const next = require('next')

const port = parseInt(process.env.PORT, 10) || 3000
const dev = process.env.NODE_ENV !== 'production'
const app = next({ dev })
const routes = require('./routes')
const handler = routes.getRequestHandler(app)

app.prepare().then(() => {
  express().use(handler).listen(port)
})
```
These are my scripts:
```
"scripts": {
    "dev": "node server.js",
    "build": "next build",
    "start": "NODE_ENV=production node server.js",
    "heroku-postbuild": "next build"
  },
```
This is my procfile:
```
web: npm start -- --port $PORT
```
These are my config variables:
```
NPM_CONFIG_PRODUCTION=false
```

![image](https://user-images.githubusercontent.com/14946081/36047319-0b84a4f2-0ddc-11e8-99c7-d2e4ce09108d.png)

**Comment by fridays** [comment]
It doesn't look like a problem with this library. Does it work with only Next.js?

**Comment by fridays** [comment]
Maybe related? https://github.com/zeit/next.js/pull/3704

**Comment by developer239** [comment]
Sorry I managed to fixed it. It was actually problem with nextjs.

https://stackoverflow.com/questions/48713444/nextjs-5-0-0-heroku-internal-server-error
