### ISSUE TITLE
Nested Routes

### ISSUE THREAD

**Issue by ed-zm** [fridays/next-routes#139]
Hi guys, How can I use nested Routes? lets say I have a `/users` route which has various subroutes. If I want to go to `/users/:id/reservations/events/` how can I do it? as I understand I will have to add it with Router.add(route, page) however I think it will call again the server the new rendered page, but I dont want to call the server again if I am already in `/users` page. 

Any Ideas?

thanks,

Ed

**Comment by fridays** [comment]
Hey, please see shallow routing: https://github.com/zeit/next.js/blob/canary/readme.md#shallow-routing

It’s the same option when using Router from `next-routes`

**Comment by davidungio** [comment]
I'd love to see an example for nested routes support. What would the `routes.js` file look like to support this? Thanks!
