### ISSUE TITLE
Next-routes + Express / CreateServer not working on local

### ISSUE THREAD

**Issue by JulienHe** [fridays/next-routes#140]
Hi everyone,

I'm trying to run next + next routes on a local development.
So everything is working pretty well but when I try to make it work with Express or even not express it can't find the pages.

![screen shot 2018-02-20 at 9 57 21](https://user-images.githubusercontent.com/718868/36402936-2324f228-1625-11e8-95f9-44cb8eb10c2b.png)
![screen shot 2018-02-20 at 9 58 07](https://user-images.githubusercontent.com/718868/36402937-23494cf4-1625-11e8-88f2-3741da07f77c.png)

I made a repo with a specific branch : https://github.com/JulienHe/firebase-next-routes-example/tree/localNext

Working with Next.js v5

Hope someone can tell me where I screw up :+1: 

Thanks!

**Comment by fridays** [comment]
Hey, it looks like the `dev` script is running the `next` command but it should instead run the custom server file like so: `node src/server.js`
