### ISSUE TITLE
Don't reload video on page change

### ISSUE THREAD

**Issue by YuriBrunetto** [fridays/next-routes#141]
Hello, guys!

I'm using FlowPlayer with `Next.js` and I want to know if is it possible to do an application that doesn't reload my video every time I click a `<Link>` with `next-routes`?

Thanks in advance. 😄

**Comment by YuriBrunetto** [comment]
@fridays can you help me with this?!

**Comment by fridays** [comment]
@YuriBrunetto I didn't have this use case yet, but it's not specifically related to `next-routes`. Please check [this issue](https://github.com/zeit/next.js/issues/88) for some discussion on how to do this

**Comment by YuriBrunetto** [comment]
Thanks for the response @fridays 😃
