### ISSUE TITLE
404 error on hard refresh of custom route

### ISSUE THREAD

**Issue by mbj36** [fridays/next-routes#148]
Hey @fridays 

Thanks for making this, it's really helpful  - Whenever i hard refresh my custom routes, it gives 404 error, when i go through `<Link>` it just works fine 

Any thing which i might be missing ?

**Comment by mbj36** [comment]
Sorry, i configured my server incorrectly

**Comment by jckw** [comment]
I was having the same problem, but turns out the solution was really simple: needed to restart the server between switching Git branches. 🙃

**Comment by lagivan** [comment]
P.S. I've figured it out myself. Adding the following code solved it for me:

```
const customRoutes = require('./routes/custom')
const expressApp = Express()
expressApp.all('/custom/*', customRoutes.getRequestHandler(app))
```

**Comment by stephane-r** [comment]
Hi guys, i've same issue with default example on the README. Anyone have fallback ?

**Comment by fridays** [comment]
How do you start the server?
