### ISSUE TITLE
original next file system routes still work? 

### ISSUE THREAD

**Issue by terencechow** [fridays/next-routes#149]
if I want to to have the parameterized route `/blog/:id` and i use the file `/page/blog.js` it appears that someone can just enter `/page/blog` in the url and it will work.

My setup is more or less a direct copy of the example in the readme. 

Anyway we can prevent this? Otherwise it apears blog.js will be pointing to 2 routes, one from the next routing system and one from next-routes

**Comment by ex3ndr** [comment]
You have to disable it in next.config.js.

**Comment by jaydenseric** [comment]
Here is the docs link: https://github.com/zeit/next.js#disabling-file-system-routing

```js
// next.config.js
module.exports = {
  useFileSystemPublicRoutes: false
}
```
