### ISSUE TITLE
Navigation is stripping UTM parameters from the url 

### ISSUE THREAD

**Issue by ernerock** [fridays/next-routes#154]
When a user arrives to the site via a link with utm tags and then navigates internally with <Link route={`internal-page/`} /> This tags are removed. Is there a way to keep these other than adding them to the route?
 
UTM_tags: 
?utm_source=Test&utm_medium=Test&utm_campaign=Test&utm_term=Test&utm_content=Test

**Comment by davidungio** [comment]
@ernerock Did you find a way to keep the parameters from being stripped?

**Comment by davidungio** [comment]
@ernerock thanks for the response. @fridays any word of in there is a way to go about not stripping existing parameters on route changes?
