### ISSUE TITLE
How to make preview route invisible in Production

### ISSUE THREAD

**Issue by rowlandekemezie** [fridays/next-routes#162]
I have a kitchen-sink route for developing/testing out common components in our application. I'm not sure how to make the route invisible on production server. I want the kitchen-sink to be visible only on development and staging.

Please, your help is appreciated

**Comment by jonespen** [comment]
Something like this?

```js
const routes = module.exports = require('next-routes')()

routes
.add('about')
.add('blog', '/blog/:slug')

if(process.env.NODE_ENV !== 'production') {
  routes.add('secret')
}
```
