### ISSUE TITLE
An error is occurred caused by type definition of next-routes

### ISSUE THREAD

**Issue by uyeong** [fridays/next-routes#164]
<img width="560" alt="2018-04-23 7 54 15" src="https://user-images.githubusercontent.com/1321707/39122678-a398afc6-4730-11e8-8e13-3b90a9ece88a.png">

Type difinition is : 

```
// next-routes.d.ts
export default class Routes implements Registry {
  getRequestHandler(app: Server, custom?: HTTPHandler): HTTPHandler;
  add(name: string, pattern?: string, page?: string): this;
  add(pattern: string, page: string): this;
  add(options: { name: string; pattern?: string; page?: string }): this;
  Link: ComponentType<LinkProps>;
  Router: Router;
}
```

But the implementation is : 

```
// index.js
module.exports = function (opts) {
  return new Routes(opts);
};
```

**Comment by gh0stonio** [comment]
Do you know when the type definition will be updated? or of this is some workaround ?

**Comment by fridays** [comment]
@disintegrator do you know what we can do here?

**Comment by disintegrator** [comment]
@UYEONG, @gh0stonio, @fridays: 
Sorry for the late reply everyone. This comment in #163 (a related PR) contains a workaround https://github.com/fridays/next-routes/pull/163#issuecomment-391673962

We are awaiting some feedback from @fridays on how to move forward on that PR
