### ISSUE TITLE
Update query in current route

### ISSUE THREAD

**Issue by luisatmaniak** [fridays/next-routes#166]
Hi,

I want to programmatically update the query string in the current route, using native next router this could be done using:

```js
// from withRouter
props.router.push({pathname: router.pathname, {query: { myParam: 'some-value' }})
``` 

This doesn't work with next-routes because `router.pathname` is ignorant of next-routes route alises.

I could make this work if we could:

1) Get current URL in next-router
2) Find a programmatic way to update query params in next-router

I also tried:

```js
import routes, { Router } from './routes'

...
// router is from withRouter
const route = routes.match(router.asPath).parsedUrl
route.query.myParam = 'my-value'
Router.pushRoute(route.format())
``

But `parsedUrl` doesn't contain the query params, they are not parsed (i.e. remain in parsedUrl.search). 

Any ideas?

**Comment by joncursi** [comment]
I'm also trying to update the query params on the existing route. My use-case is a search page, where the user can toggle on/off various filters.

A good example of this is cars.com: https://www.cars.com/for-sale/searchresults.action/?mdId=26381&mkId=20021&page=1&perPage=20&rd=20&searchSource=GN_BREADCRUMB&shippable=false&showMore=true&sort=relevance&zc=08096

**Comment by joncursi** [comment]
@luisatmaniak did you happen to find a method that can achieve this?

**Comment by renato** [comment]
I'm sorry, I'm probably misunderstanding the issue here, but I'm using `Router.replaceRoute` on the pages I need the search string to be on the url's query params.

**Comment by skywickenden** [comment]
Is there a resolution or at least a work around to this yet?

**Comment by tommhuth** [comment]
Any news on this? Changes in query params should be reflected in the url as well., particularly if this is available in pure NextJS.

**Comment by mapsgeek** [comment]
i don't understand how come working with query params is so primitive in nextjs, simple tasks like removing a certain param should be achieved by just setting the param to null or undefined this is how it simply works in other frameworks like nuxtjs but that's not the case if you want to delete a param you have to do
let's say we have url= `...?x=1&y=2`
```
delete router.query['x']
router.push({
  query: {
   //keeping the rest of the params in the route you only want to reset the x filter
  ...router.query
  },
});
```
but this won't work unless you actually add a second param to the query like
```
delete router.query['x']
router.push({
  query: {
   //only by providing a new param the url will update! it will never update with an empty object
  ...router.query,
  whatever: whatevervalue
  },
});
```
which isn't always the case when you are creating a dynamic filtering, filter x can be the last param available and the user needs to reset it so you simply want the query params to be an empty object which next doesn't update the url if it's an empty object!
