### ISSUE TITLE
Preserve localized path prefix

### ISSUE THREAD

**Issue by smkhalsa** [fridays/next-routes#174]
I have an app-wide url structure for localized pages:

`/:locale/{rest-of-path}`

Unless the user has selected a new language, the `locale` will always be the same as the previous route. Is there anyway to retain the previous `locale` part of the route without having to pass the current `locale` to each component?

**Comment by einarlove** [comment]
Could suggest you supply it with context and use your own Link component instead of next-routes own.

```js
import React from 'react'
import { Link as RoutesLink } from '../routes'
import { CurrentOrganizationContext } from '../lib/withCurrentOrganization'

export default props => (
  <CurrentOrganizationContext.Consumer>
    {currentOrganizationId => (
      <RoutesLink {...props} params={{ organizationId: currentOrganizationId, ...props.params }} />
    )}
  </CurrentOrganizationContext.Consumer>
)
```
