### ISSUE TITLE
is there any way to use this together with withRouter()

### ISSUE THREAD

**Issue by reflog** [fridays/next-routes#175]
...and if not, how should I inject the router into current component? (for example to access current path)

**Comment by mmiszy** [comment]
You can use `withRouter`. Did you get any errors?

**Comment by reflog** [comment]
no errors, just curious if the injected router will be the correct one (from routes.js) and the the default one

**Comment by mmiszy** [comment]
It works. The only caveat is it won't rerender on when you have a dynamic route and the dynamic part changes. You have to use Router events for that.
(Or at least I have that problem, but maybe I'm doing something wrong)

**Comment by reflog** [comment]
gotcha. thanks!

**Comment by haotangio** [comment]
There is problem

I cannot use `this.props.router.push`, it reload the browser instead of keeping single page navigation.

**Comment by bmathews** [comment]
@haotangio @guiihlopes, try router.pushRoute instead of router.push
