### ISSUE TITLE
different dynamic routes based per domain name

### ISSUE THREAD

**Issue by zsolt-dev** [fridays/next-routes#179]
Hi,

I am not sure if next-routes is the good solution for me, but I am building an web that will be localised in 10+ languages (each language on dedicated domain) and would like to serve them from the same next.js server.

Is there a way to use define next-routes based on domain name?

for example:
us web site on example.com:
routes
.add('about')
.add('blog', '/blog/:slug')

and for example.es
routes
.add('aboutInSpanish')
.add('blog', '/blogInSpanish/:slug')

???

Also it would need to work on client too.

THank you

**Comment by DonStanislas** [comment]
Des nouvelles de ce sujet ?

**Comment by DonStanislas** [comment]
@zsolt-dev you find the solution ?
