### ISSUE TITLE
Is there any function like  Routes.goback ()  to go back or pop a route ?

### ISSUE THREAD

**Issue by jpca999** [fridays/next-routes#180]

**Comment by reergymerej** [comment]
[This](https://github.com/fridays/next-routes/blob/master/src/index.js#L110-L113) shows how some of the [core methods](https://github.com/zeit/next.js/blob/canary/packages/next-server/lib/router/index.js#L20) have been wrapped.  There is no core method for `pop`.

The underlying next/router is exposed, though, so you can simply call [`Router.back`](https://github.com/zeit/next.js/blob/canary/packages/next-server/lib/router/router.js#L131-L133) to go back to the previous route.
