### ISSUE TITLE
Is it possible to get the previous route?

### ISSUE THREAD

**Issue by dextermb** [fridays/next-routes#183]
🤔

**Comment by reergymerej** [comment]
#180 shows how to go back, but it doesn't return the new route object.

**Comment by vaibhavi3t** [comment]
Hi,
I also have a use case where I need to know about the previous page.
I'm using `next-routes` in my nextjs app. 
Any idea how I can achieve this or any default support in the library?

**Comment by reergymerej** [comment]
I can move on with my life now.  :D
