### ISSUE TITLE
Feature request: Route guards

### ISSUE THREAD

**Issue by dextermb** [fridays/next-routes#187]
I'd like to see some form of route guards added, this would check for a truthy statement **before** attempting to load the component. 

This would be useful, with server side guards for the initial load, as when using Link's `route` attribute it does not reload the page.

Ideal example usage:
```js
const routes = module.exports = require('next-routes')();

const guard = function(route) {

    // Check JWT tokens
    // ...etc
    return true;
}

// Singular guards
routes.add('/', 'index').guard(guard);

// Multiple guards
routes.add('/', 'index').guard([guard, guard]);
```

**Comment by dextermb** [comment]
I've gone back to doing something like this for now...

```
import React from 'react';
import Empty from '../components/empty';

const withAuth = Component => {
	return class extends React.Component {
		constructor(props) {
			super(props);
		}

		// noinspection JSUnusedGlobalSymbols
		static async getInitialProps() {
			return {
				authenticated: true
			};
		}

		render() {
			const authenticated = this.props.authenticated;

			return !authenticated
				   ? <Empty redirect={'/login'}/>
				   : <Component/>;
		}
	};
};

export default withAuth;
```

But I'd definitely like to see guards implemented.

**Comment by fridays** [comment]
I think getInitialProps is the best place to do this to have it work on both server and client routing

**Comment by dextermb** [comment]
@fridays Sure, I like `getInitialProps` but creating a full high order component for each guard would get pretty messy and make the application big. I wonder if it's possible to have `next-routes/guard` to be a high order component that accepts functions to compare.

This would wrap `index` in a high order component that would compare a single or multiple guards.
```
routes.add('/', 'index').guard(guard);
```

Thoughts?

**Comment by larron** [comment]
Perfect, I'd also suggest that the guard function can be async

**Comment by bflopez** [comment]
@dextermb Hey is there any reason this was closed? Did you figure out how to guard? Looking to do exit intent popup when a user abandons cart.

**Comment by dextermb** [comment]
> @dextermb Hey is there any reason this was closed? Did you figure out how to guard? Looking to do exit intent popup when a user abandons cart.
> 
> EDIT: I see in the docs it can be done. https://nextjs.org/docs/#intercepting-popstate

I closed it as I used `getInitialProps` as suggested by @fridays. While I still would like to see this feature added, I'll probably end up doing it in my own fork as this repository doesn't seem to be very active.
