### ISSUE TITLE
onRouteChangeComplete/Error not fired

### ISSUE THREAD

**Issue by mxmtsk** [fridays/next-routes#189]
I recently made the switch from the built in router to `next-router` but the `Router` event handlers aren't fired anymore.

`onRouteChangeStart` does get fired just fine.

My `routes.js`
```JS
const routes = (module.exports = require('next-routes')());

const allowedSlugs = 'bundestagswahl-2017|landtagswahl-niedersachsen-2017';

routes
  .add('impressum')
  .add('datenschutz')
  .add('kontakt')
  .add('presse')
  .add('wahlen')
  .add('wahl', '/wahlen/:slug(' + allowedSlugs + ')', 'wahl');

module.exports = routes;

```

In my Header file (to trigger loading progress bar):
```JS
import { Router } from '../../routes';

Router.onRouteChangeStart = url => {
  console.log(`Loading: ${url}`); // eslint-disable-line
  NProgress.start();
};
Router.onRouteChangeComplete = () => {
  NProgress.done();
  console.log('done');
};
Router.onRouteChangeError = e => {
  NProgress.done();
  console.log(e);
};
```

**Comment by RustyDev** [comment]
I was having the same issue with the same setup. Turned out that I had two `Router.onRouteChangeComplete` event listeners in my code. I combined them and it solved my issue.

**Comment by Msea** [comment]
It looks to me like this functionality is not supported on the next-routes object. However, it can be added to the underlying router, in your case that would look like
```
import { Router } from '../../routes';

Router.Router.onRouteChangeStart = url => {
  console.log(`Loading: ${url}`); // eslint-disable-line
  NProgress.start();
};
Router.Router.onRouteChangeComplete = () => {
  NProgress.done();
  console.log('done');
};
Router.Router.onRouteChangeError = e => {
  NProgress.done();
  console.log(e);
};
```
I just added this pull request https://github.com/fridays/next-routes/pull/198 to add _a_ top level syntax, albeight not the same one used by "next".

**Comment by fridays** [comment]
@mxmtsk you say `onRouteChangeStart` gets fired, could you verify the issue is different than described in https://github.com/fridays/next-routes/issues/189#issuecomment-397048690 ?

@Msea Router events should just work like in Next.js, in your example above could you show routes.js?

**Comment by mxmtsk** [comment]
@RustyDev Thank you very much. That was indeed causing the issue for me! (@fridays)
