### ISSUE TITLE
Issue with next-routes in production mode on iOS 9.3.

### ISSUE THREAD

**Issue by wdifruscio** [fridays/next-routes#194]
I am running next-routes on nextjs 6, great package! Unfortunately I am having an issue I cannot seem to find the answer for. I had several users complain that the app was not working properly on their apple devices. After investigating I noticed that on ios 9.3 (have not tested other versions) the client side routing did not work. 

When I ran locally in dev environment I noticed the links worked fine, even testing on ios 9.3. When running again using build and production mode locally, I was able to replicate this not working. It seems the client side routing does not work in production mode on safari on ios 9.3. There were no console errors or anything like that and including a global polyfill did not change anything either.

Thoughts?

EDIT:

Upon further testing and debugging, my team discovered we were able to remove this error by removing UglifyJS from webpack config in nextjs production mode - unsure where exactly the problem lies

**Comment by willcodes** [comment]
Upon further testing and debugging, my team discovered we were able to remove this error by removing UglifyJS from webpack config in nextjs production mode - unsure where exactly the problem lies

**Comment by fridays** [comment]
Thanks for reporting. Could you check if this is happening too with pure next.js links or only when using next-routes?
