### ISSUE TITLE
Critical need to fix that Object.assign issue

### ISSUE THREAD

**Issue by adriendomoison** [fridays/next-routes#207]
Hi!

Thanks a million for this amazing project.

Following #142 and #53 there is an urgent need to fix `Object.assign`, this needs at least to be polyfilled ASAP https://github.com/fridays/next-routes/blob/08e8bbeaa76c5ec194abea388a193bedac7f35fc/src/index.js#L96

This makes Googlebot crash 😬 so that's why it's pretty important 😅

Full error on Chromium 38:

![Full error on Chromium 38](https://user-images.githubusercontent.com/9092210/42309965-044d8d90-7fef-11e8-9e0e-9923946710a4.png)

The result for us is that the Next.js error page is appended at the end of the current page when the page is crawled by Googlebot

![Googlebot error](https://user-images.githubusercontent.com/9092210/42309993-1698d860-7fef-11e8-8054-cfe70c64399b.png)

And as a direct result, that's what happened:

![Result on ranking](https://user-images.githubusercontent.com/9092210/42310053-458eb144-7fef-11e8-8d24-b9c98a312083.png)

Google fixed the title with time, but you can still reproduce what Googlebot sees by navigating to our website on Chromium 38 or other old browsers.

I was able to fix in on my local environment by replacing `Object.assign(newProps, _this2.findAndGetUrls(nameOrUrl, params).urls);` (line 175) in `node_modules/next-routes/dist/index.js` by
```
if (!Object.assign) {
      Object.defineProperty(Object, 'assign', {
          enumerable: false,
          configurable: true,
          writable: true,
          value: function(target) {
              'use strict';
              if (target === undefined || target === null) {
                  throw new TypeError('Cannot convert first argument to object');
              }
  
              var to = Object(target);
              for (var i = 1; i < arguments.length; i++) {
                  var nextSource = arguments[i];
                  if (nextSource === undefined || nextSource === null) {
                      continue;
                  }
                  nextSource = Object(nextSource);
  
                  var keysArray = Object.keys(Object(nextSource));
                  for (var nextIndex = 0, len = keysArray.length; nextIndex < len; nextIndex++) {
                      var nextKey = keysArray[nextIndex];
                      var desc = Object.getOwnPropertyDescriptor(nextSource, nextKey);
                      if (desc !== undefined && desc.enumerable) {
                          to[nextKey] = nextSource[nextKey];
                      }
                  }
              }
              return to;
          }
      });
  } else {
      Object.assign(newProps, _this2.findAndGetUrls(nameOrUrl, params).urls);
  }
```

The great news is that to fix this, it looks like you just need to merge #143 😁

Thanks!!

**Comment by oliviertassinari** [comment]
Same problem here. I'm gonna keep a local fork on our project.

**Comment by mmiszy** [comment]
You can add a polyfill for Object.assign to your project if you need it. Would that solve the problem?

**Comment by oliviertassinari** [comment]
@mmiszy Most people already have the Babel ponyfill, an extra polyfill is code duplication.

**Comment by mmiszy** [comment]
@oliviertassinari I'm suggesting you should import the polyfill for `Object.assign` from Babel (from core-js) if you need it. `import 'core-js/features/object/assign'` should do I guess?
