### ISSUE TITLE
Redux state is lost when using /page/:slug

### ISSUE THREAD

**Issue by jan0991** [fridays/next-routes#220]
I am using next-redux-wrapper and it preserves state fine as long as I am switching between same level pages. For example:

`domain.com -> domain.com/profile`
`domain.com/profile -> domain.com/some-other-page`

However, state get's lost(redux re-creates new store) when I do:
`domain.com -> domain.com/profile/:slug`

**Comment by adred8** [comment]
This is happening for all pages to me. With browser back and forth, the state gets reset. Can you tell how you solved this issue ?

**Page A :**
![screenshot 2018-12-05 at 4 06 59 pm](https://user-images.githubusercontent.com/5622964/49510923-b84fc180-f8af-11e8-9c06-285dbdd7571c.png)

**Page B :** 
![screenshot 2018-12-05 at 4 07 06 pm](https://user-images.githubusercontent.com/5622964/49510937-bf76cf80-f8af-11e8-9711-57dfe43e962d.png)

**Comment by kokno** [comment]
@jan0991 did you solve the problem ? If yes, how ? Thank you

**Comment by VadyaVL** [comment]
@kokno check using Link from '.../routes' or 'next/link',

**Comment by zamhaq** [comment]
@kokno @VadyaVL how did you guys fix this issue?

**Comment by 13MS** [comment]
I'm running into the same issue although I am not using Redux. Does anyone have a solution for this?
