### ISSUE TITLE
getInitialProps() becomes undefined

### ISSUE THREAD

**Issue by KosukeYoshimura** [fridays/next-routes#227]
Hello !

I try to get params by getInitialProps().

However, when I try to get that like this,

/pages/books/show.js
```
static async  getInitialProps(props) {

        console.log(props.query)

    }

```

it turned error like this.

```
"Show.getInitialProps()" should resolve to an object. But found "undefined" instead.

```

routes.js↓
```
const routes = require('next-routes')();

routes
    .add('/books/peterThiel', '/books/peterThiel')
    .add('/:name/books/show', '/books/show');  <----- want to use this "name" params

module.exports = routes;
```

Can anyone give me advice?

**Comment by msreekm** [comment]
i think you have return from getinitialprops
static async  getInitialProps(props) {
        console.log(props.query)
return {name: props.query.name} 


    }

**Comment by KosukeYoshimura** [comment]
do u mean I did not return name params?

**Comment by msreekm** [comment]
i meant you have to return something from getInitialProps(0 method.
https://github.com/zeit/next.js#fetching-data-and-component-lifecycle

**Comment by lauriskuznecovs** [comment]
You can try at least:
```
static async getInitialProps ({ query }) {
    return await query
}
```

**Comment by hieunguyendut** [comment]
I'm facing the same problem. I return a pathname from getinitialProps() functions but It showed undefined in render() function. Any one have answer for this issue?

**Comment by hieunguyendut** [comment]
> static async getInitialProps ({ query }) {
>     return await query
> }

I tried but still show undefined

**Comment by lauriskuznecovs** [comment]
> > static async getInitialProps ({ query }) {
> > return await query
> > }
> 
> I tried but still show undefined

Which Next.js version are you using?

**Comment by Babatunde50** [comment]
I think you need to return an object. It can be an object of any kind, you just need to return an object for getInitialProps to work.
