### ISSUE TITLE
Options Inconsistence 

### ISSUE THREAD

**Issue by jackypan1989** [fridays/next-routes#229]
I wanna update query in the same page, so I have to use shallow option.
But the example below shows that inconsistency (only works with routeName) 

Routes Config
```
.add('explore', '/explore', 'mypages/explore')
```

### Work
```
Router.replaceRoute('explore', { myParams }, { shallow: true })
```

### Not work
```
Router.replaceRoute('/explore', { myParams }, { shallow: true })
```

**Comment by fridays** [comment]
In the second example, use `.replace` instead of `.replaceRoute`
