### ISSUE TITLE
Shallow Routing calls getInitialProps if not using named route + params

### ISSUE THREAD

**Issue by kennand** [fridays/next-routes#236]
Heads up for people using shallow routing:

I notice that if I stick a console log in my getInitialProps, it gets hit if I use normal URL routing instead of route name + params. 

Router.pushRoute('/a/:slug') - calls getInitialProps
Router.pushRoute('aName', { slug: 'aSlug' }) - does not call getInitialProps

**Comment by mherodev** [comment]
Have you had success with shallow routing? I'm finding two issues:

1. If I navigate back out of a shallow route (e.g. back from `/about#test` to `/about`), `getInitialProps` is still called even though it's the same page component being viewed.
2. If I navigate back from a deep route into a shallow route (e.g. back from `/blog` to `/about#test`), I get an error and the back navigation does not occur.
