### ISSUE TITLE
Is this project being maintained or has it been abandoned?

### ISSUE THREAD

**Issue by alexpareto** [fridays/next-routes#244]

**Comment by elliottsj** [comment]
@fridays Would you be open to adding additional maintainers to this project?

For now, I am maintaining my own fork over at https://github.com/elliottsj/next-routes / https://www.npmjs.com/package/@elliottsj/next-routes. I don't like the idea of forcing whole the community to move to a fork though, so my intention is to keep this fork maintained until _fridays/next-routes_ becomes maintained again, or @fridays can comment on the future of this package.

So far, I have addressed https://github.com/fridays/next-routes/issues/181 in my fork. Please create issues / pull requests on my fork if you'd like them addressed.

**Comment by mherodev** [comment]
Thanks for setting that up @elliottsj! I may be opening a PR against your fork shortly.

**Comment by maggo** [comment]
Ping! Happy new year! 🎉 

@fridays it would be nice if you added @elliottsj / the Yolk team as maintainers, they seem to be super active (Thank you!)

I'd love to use this project, but am concerned about a future upgrade to next v8

**Comment by usergenic** [comment]
*gentle ping*

**Comment by drewlustro** [comment]
also would like to know

**Comment by fridays** [comment]
Hi everybody, sorry for the delay and thank you for your patience. I just added @elliottsj as maintainer to the project.

Currently I'm unable to find the time this project deserves. Please let me know if I should add more people or whatever I can do to make it easy for you. Thanks

**Comment by elliottsj** [comment]
Thanks @fridays! In the coming days, I'm planning on merging the improvements in my fork back upstream. There are a lot of open issues & PRs in this repo, so I won't be able to get to all of them, but I'll try my best.

@fridays Would you like to continue to be in charge of publishing new versions to npm? If you like, I can take care of that too; my npm username is `elliottsj`: https://www.npmjs.com/~elliottsj

**Comment by gabrieledarrigo** [comment]
Ciao guys, so is this still matained?

**Comment by damianfrizzi** [comment]
Another inactive maintainer @elliottsj?

**Comment by abrkn** [comment]
@elliottsj Where is your fork?

**Comment by felixmosh** [comment]
@elliottsj, why you are not merging your changes to here?

**Comment by elliottsj** [comment]
Sorry folks, I've been busy with work & life things, and I haven't had the time to dedicate to this project recently. I've under-delivered on my last message, and I apologize for that.

The PR to merge back upstream is [here](https://github.com/fridays/next-routes/pull/292), and the next steps are to [fix the build](https://travis-ci.org/fridays/next-routes/jobs/503182032), then merge, publish version 3.0.0, disable Greenkeeper, and enable Renovate, as long as @fridays has no objections.

I can't promise that I'll be able to take this on in the near future, so it would be appreciated if someone else can step up.

**Comment by felixmosh** [comment]
@elliottsj thanx for explaining

**Comment by ItsWendell** [comment]
Looking forward to seeing this updated again!

**Comment by mehmetnyarar** [comment]
I couldn’t make it work neither with this repo nor `@yolkai`. so i basically copied the `src/index.js` to my project, add typings, made some small modifications, and using it now w/o problem.

You can check [this gist](https://gist.github.com/mehmetnyarar/800111eee5d9b1462012dff61f29c82f).

**Comment by elliottsj** [comment]
[Dynamic routes are now natively supported by Next.js](https://nextjs.org/blog/next-9#dynamic-route-segments), so next-routes is no longer necessary for most use cases.

**Comment by emileber** [comment]
> next-routes is no longer necessary for **the most simple** use cases.

_next-routes_ should have been in Next from the beginning but it was not. Next.js leaves us empty handed when we need a little more configuration with routing when we have constraints out of our control, like not having a server to render on.

Unfortunately, the new dynamic routes are far from being enough to ditch _next-routes_.

**Comment by YYCoder** [comment]
> > next-routes is no longer necessary for **the most simple** use cases.
> 
> _next-routes_ should have been in Next from the beginning but it was not. Next.js leaves us empty handed when we need a little more configuration with routing when we have constraints out of our control, like not having a server to render on.
> 
> Unfortunately, the new dynamic routes are far from being enough to ditch _next-routes_.

I agree 😆. Personally, I prefer centralized routing declaration like next-routes to file path based routing.

**Comment by martpie** [comment]
I agree `next-routes` is not going anywhere (regex check are too much of a powerful feature for example).

It is worth noticing that the [server(less) middleware RFC](https://github.com/zeit/next.js/issues/7208) will probably solve 90% of the problem `next-routes` solve.

**Comment by caribou-code** [comment]
I agree that the new dynamic routing in NextJS 9 isn't sufficient for all cases. I'm building a bilingual site where the different locale versions of a URL need to point to the same file/path. That can't be done easily without something like next-routes.

Kind of depressing that this issue has been open for 9 months and there's still no commits in a year. This package has around 50k monthly npm downloads and growing.

**Comment by elliottsj** [comment]
I agree that next-routes is still useful for more complex use cases. Unfortunately neither @fridays nor myself have the resources to keep this project maintained at the moment, so a good way to get next-routes maintained again is for someone in the community who actively uses next-routes to volunteer to take over maintenance.

**Comment by caribou-code** [comment]
There's currently 30 PRs open on this project so it looks like there's no shortage of people willing to contribute and get involved. Many are from the same people. Might I suggest handing over control to one/some of them so some of the PRs and issues can make some progress?

**Comment by martpie** [comment]
`@yolkai/next-routes` looks like the most active fork.

https://www.npmjs.com/package/@yolkai/next-routes

**Comment by maggo** [comment]
The fork you linked has been archived @martpie: https://github.com/yolk-hq/next-routes#readme

There used to be a [PR](https://github.com/fridays/next-routes/pull/292) to merge it back, but it was closed. What's the reasoning here @elliottsj? Maybe this could be merged to make it easier for a future maintainer?

Sadly I don't have an active next project right now and also lost track over what's in core and what needs to be solved with third-party libraries, so I won't be able to maintain it properly. I hope to get back into it soon :)

**Comment by Timer** [comment]
Hey, Next.js Core Team member here! We'd be interested in taking over maintenance of this package if you'd be willing to grant myself access to the repo and [npm](https://www.npmjs.com/~timer).

**Comment by fridays** [comment]
Hi, that's great news! I just added you to the repo and npm.

**Comment by janbiasi** [comment]
@Timer any updates available 😄 ?

**Comment by gabrielsch** [comment]
> Hey, Next.js Core Team member here! We'd be interested in taking over maintenance of this package if you'd be willing to grant myself access to the repo and [npm](https://www.npmjs.com/~timer).

That's exciting, I'm pretty sure a lot of companies are using this package because of its way to structure app routes. My team for example are still on Next8 because of this. Please let us know what are your plans with next-routes! Thanks

**Comment by fruitmim** [comment]
Looking forward to the updates.

**Comment by fabn** [comment]
@Timer any news? Is this something is still worth to invest?
