### ISSUE TITLE
Typescript types are not up to date with API

### ISSUE THREAD

**Issue by seawatts** [fridays/next-routes#248]
The following method are not exported with the type definitions

```
class Routes {
  findByName (name)
  match (url)
  findAndGetUrls (nameOrUrl, params)
  getLink (Link)
  getRouter (Router)
}
```

**Comment by Weffe** [comment]
Is this still unsolved? I could make a PR with the added typings if needed.

**Comment by jack-sf** [comment]
There's a PR in https://github.com/fridays/next-routes/pull/277 but this repo seems to be abandoned for now https://github.com/fridays/next-routes/issues/244
