### ISSUE TITLE
How to handle % and # characters on parameter

### ISSUE THREAD

**Issue by PenguinScola** [fridays/next-routes#256]
I am developing tag tracking system on NextJS and my application URL need to receive parameter as tag name that contains % and # characters. For example, "C#", "100%" etc.

So its URL will look like below.

> https://myapp.com/tag/C#
> https://myapp.com/tag/100%
> https://myapp.com/tag/harry_potter

For "C#", I have found that query value from getInitialProps function will be "C" only (# character is cut)
and for "100%", I have found that next-routes return error as below. URI malformed has occurred on decodeURIComponent function because of % character.

![image](https://user-images.githubusercontent.com/18202926/48536863-659f6d00-e8e2-11e8-8c64-a0180b51e921.png)

If I need to handle both of characters, could you please suggest how can I handle them by using next-routes?

**Comment by karolisgrinkevicius** [comment]
I'm having the same question as @PenguinScola.

**Comment by nagibmahfuj** [comment]
Any solution to this issue, I'm also having this problem :(

**Comment by nagibmahfuj** [comment]
Lastly I did this to resolve on my server.js file.
```javascript
const server = express();
server.use(function(req, res, next) {
    try {
        decodeURIComponent(req.originalUrl);
    } catch (err) {
        res.redirect(301, "/");
        next(err);
    }
});
// Do other stuffs
```
