### ISSUE TITLE
Wrong route and pathname

### ISSUE THREAD

**Issue by elvishp2006** [fridays/next-routes#257]
I registered the following route: 
```javascript
routes.add({
  name: 'mensagens',
  pattern: '/mensagens',
  page: 'quotes',
});
```

When I check the router param on Router (imported from 'routes') object, I'm getting the follow params:

![captura de tela de 2018-11-21 18-20-27](https://user-images.githubusercontent.com/7463100/48866491-27aab900-edba-11e8-9fe4-eeb32ca2dcbb.png)

I'm acessing `/mensagens` but I'm getting `/quotes` as route and pathname

**Comment by bigredwill** [comment]
Next.js Router needs to know these things because that is how it is routing internally. The `asPath` property is how the route appears, and the `pathname` and `route` properties are used to route to the correct component.

**Comment by Pashozator** [comment]
`/mensagens` in this example should be accessible somehow too.

**Comment by santiagoramirez** [comment]
Would is be possible to have a parameter with the path extracted from the query string? Currently, you could get `/mensagens` from `asPath`, but when you have a query string it will return that as well when you may only want the base route of `/mensagens`
