### ISSUE TITLE
Incompatible with next@canary

### ISSUE THREAD

**Issue by joncursi** [fridays/next-routes#262]
There appears to be a breaking change in the current canary branch of next.js that needs to be discussed / addressed here. Custom servers no longer boot up when using next-routes:

https://github.com/zeit/next.js/pull/4851#issuecomment-444821952

**Comment by Enalmada** [comment]
@fridays Is there something that next-routes could do to become compatible with next@canary?

**Comment by EduardoHidalgo** [comment]
I have the same issue! I had to upgrade to canary version because next has problems with now.sh.

Any approach?

**Comment by timneutkens** [comment]
Same issue as https://github.com/fridays/next-routes/issues/274

I've solved this on the Next.js side of things.
