### ISSUE TITLE
On load, pattern "/test" works but "/test/test" doesn't

### ISSUE THREAD

**Issue by thmsgbrt** [fridays/next-routes#263]
Hi everyone,

I found something that looks strange for me as I don't really understand with it's not working.
Here is a route.js example of my app:

```
const nextRoutes = require('next-routes');
const routes = require('next-routes');

module.exports = routes()
  .add('index', '/', 'index')
  .add('test', '/test', 'test')
  .add('hello', '/test/hello', 'hello')
```

So, here are the scenarios:
- Navigation through `<link route="xxx" />`  **works absolutely fine** for the 3 routes.
- Landing directly to `/` or `/test` **works great** but landing to `/test/hello` **will lead to a 404.**

Is this a bug or is there something I don't understand with the pattern ?

Thanks for your help!

**Comment by aluminick** [comment]
Why you have 2 `require('next-routes')`? Maybe you don't have the hello page inside .pages.

**Comment by thmsgbrt** [comment]
Hi Aluminick,
Actually, the issue was on my end.
Some days ago, I switched back to the `next start` starting scrip because of some issues I had in my code. Switched fixed the errors I had but was responsible of the 404 errors.

I'm closing the issue... Sorry!!
