### ISSUE TITLE
Server rendered 404 page

### ISSUE THREAD

**Issue by highlabs** [fridays/next-routes#267]
Hi!

I'm trying to use slug in my article page. It's work when I click in article link, but when I enter directly from URL or I reload the page, I get 404 error.

I tried with and without express server using both of examples in `next-routes` README.

My `/routes.js` file:
```js
const routes = require('next-routes');

module.exports = routes().add({
  name: 'post',
  pattern: 'posts/:slug-:id([^-]+)',
  page: 'post_public'
});


```

My `server.js` file:
```js
const next = require('next')
const routes = require('./routes')
const app = next({dev: process.env.NODE_ENV !== 'production'})
const handler = routes.getRequestHandler(app)
const express = require('express')
app.prepare().then(() => {
  express().use(handler).listen(3000)
})
```

package.json
```json
{
  "name": "create-next-example-app",
  "scripts": {
    "dev": "node server.js",
    "build": "next build",
    "start": "NODE_ENV=production node server.js"
  },
  "dependencies": {
    "express": "^4.16.4",
    "next": "^7.0.2",
    "next-routes": "^1.4.2",
    "react": "^16.6.3",
    "react-dom": "^16.6.3"
  }
}
```
Any ideas what I'm doing wrong?

**update**

Version with error: https://github.com/highlabs/next-routes-test
Live url: https://create-next-example-app-bftspwtpwy.now.sh/

**Comment by anatoliykot** [comment]
I have the same error, but on production build

**Comment by dmitrymikheev** [comment]
+

**Comment by aminkhademian** [comment]
the same error

**Comment by highlabs** [comment]
This project is dead?

**Comment by Victorkangsh** [comment]
same error

**Comment by aluminick** [comment]
You have no backend route that's why it's 404. checkout [next tutorial](https://nextjs.org/learn/basics/server-side-support-for-clean-urls/information-on-url)

**Comment by seawatts** [comment]
Same thing

**Comment by dstrtop1** [comment]
anybody got a workaround at least? in my case it works in dev, but not in production, in addition it automatically adds '/' in every url in production

**Comment by luyx2412** [comment]
Same issue!

**Comment by dstrtop1** [comment]
> Same issue!

I solved it by running node server near my nginx on server like as I do it usually on my localhost
