### ISSUE TITLE
ie 11 error

### ISSUE THREAD

**Issue by philipheinser** [fridays/next-routes#27]
We get the following error in ie 11 `object doesn't support this property or method find`. We only use nextjs and next-routes. Maybe we need to chnage your babel Settings? https://github.com/zeit/next.js/issues/473

**Comment by HaNdTriX** [comment]
Lets wait for https://github.com/zeit/next.js/pull/1808 than these kinds of problems will be solved by [babel-preset-env](https://github.com/babel/babel-preset-env).

**Comment by sfrieson-tm** [comment]
It seems next.js is polyfilling Object.assign now, but i'm still getting the error in IE11. I'm pretty sure the call is coming from next-routes.

**Comment by sfrieson-tm** [comment]
I have now added Polyfill.io which claims to support polyfilling the find method, but I am still getting the error and when I look at the source, it seems to be coming from the `findByName` [method definition](https://github.com/fridays/next-routes/blob/b2b2d91f162c218aab2116a7e0b788072608c0a1/src/index.js#L25).

This is currently breaking my IE11 version.  Could you please review or suggest other steps I could take.

**Comment by HaNdTriX** [comment]
https://github.com/fridays/next-routes/pull/37
