### ISSUE TITLE
Support Next.js v8

### ISSUE THREAD

**Issue by jaydenseric** [fridays/next-routes#274]
`next-routes` imports from `next/link`:

https://github.com/fridays/next-routes/blob/1.4.2/src/index.js#L4

But in Next.js v8.0.0-canary.3 that file contains ESM, presumably because Next.js expects it will always be imported within a Next.js project via a Webpack build:

https://unpkg.com/next@8.0.0-canary.3/dist/client/link.js

That causes this runtime error on the server:

```
[redacted]/node_modules/next/dist/client/link.js:2
import { resolve, format, parse } from 'url';
       ^

SyntaxError: Unexpected token {
```

Presumably `import NextRouter from 'next/router'` would have the same issue.

**Comment by timneutkens** [comment]
This is still on my list of things to fix. However next-routes is importing next/link inside the custom server, which is slightly weird/wrong anyway.

**Comment by EduardoHidalgo** [comment]
this issue was fixed by 8.0.0-canary.7 (: i validated.

**Comment by amankakar** [comment]
thank @EduardoHidalgo  you have saved my day..

**Comment by fridays** [comment]
Thank you! Yeah Link on server-side doesn't make sense, it's not used there at all, it's just in the same file. PR welcome

**Comment by corysimmons** [comment]
Can this be closed since it works in 8?

**Comment by EduardoHidalgo** [comment]
Yes 😀
