### ISSUE TITLE
<Link prefetch>

### ISSUE THREAD

**Issue by sedubois** [fridays/next-routes#28]
From reading the README, it's not clear if Link supports Next.js' prefetch option?

Thanks 🙂

**Comment by HaNdTriX** [comment]
It does since it just extends the `next/link` link.

https://github.com/fridays/next-routes/blob/master/src/index.js#L54-L64

**Comment by sedubois** [comment]
OK, thanks! Don't know if documentation should reflect this?

**Comment by HaNdTriX** [comment]
Since you stumbled over it, I believe yes. Actually I also had to check the code to be sure.
So I chose a more general wording.

> Other props like `prefetch` will work as well.

If `next/link` will get more props we don't need to update the docs.
