### ISSUE TITLE
Browser refresh renders 404 page on dev server

### ISSUE THREAD

**Issue by ssolanki** [fridays/next-routes#290]
My routes are like this:
```
// routes.js
module.exports = routes()
    .add("about")
    .add("city", "city/:city", "city")
```

My server is running on port `5010` and dev server is running on `5000`.

When I visit a route /city/city1 and refresh then it renders the respective city page on the server but on the client(i.e port `5000`) it throws 404 page.

For the client, refresh works only if I visit /city?city=city1

**Comment by Bygonaut** [comment]
Need more info, what does your package.json look like and your server.js page look like?

**Comment by ssolanki** [comment]
package.json
```
"scripts": {
		"dev": "env-cmd ./.env.local next -p 5000",
		"build:staging": "env-cmd ./.env.staging next build",
		"build": "env-cmd ./.env.production next build",
		"start": "NODE_ENV=production node server",
		"lint": "eslint ./",
		"lint:fix": "eslint ./ --fix",
		"precommit": "npm run lint"
	},
	"dependencies": {
		"@emotion/core": "^10.0.7",
		"@emotion/styled": "^10.0.7",
		"@rebass/grid": "^6.0.0-7",
		"axios": "^0.18.0",
		"emotion": "^10.0.7",
		"emotion-server": "^10.0.7",
		"emotion-theming": "^10.0.7",
		"es6-promise": "^4.2.5",
		"express": "^4.16.4",
		"isomorphic-unfetch": "^3.0.0",
		"next": "^8.0.0",
		"next-redux-saga": "^3.0.0",
		"next-redux-wrapper": "^3.0.0-alpha.1",
		"next-routes": "^1.4.2",
		"react": "^16.8.1",
		"react-dom": "^16.8.1",
		"react-redux": "^6.0.0",
		"redux": "^4.0.1",
		"redux-logger": "^3.0.6",
		"redux-saga": "^1.0.1",
		"styled-system": "^3.2.1"
	},
      devDependencies: {}
```

// server.js 
```
const express = require("express")
const next = require("next")

const routes = require("../routes")

const port = parseInt(process.env.PORT, 10) || 5010
const dev = process.env.NODE_ENV !== "production"
const app = next({ dev })
const handler = routes.getRequestHandler(app)

app.prepare().then(() => {
    const server = express()
    server.use(handler)
    server.get("*", (req, res) => {
        return handler(req, res)
    })

    server.listen(port, err => {
        if (err) throw err
        console.log(`Server ready on http://localhost:${port}`)
    })
})

```

**Comment by ssolanki** [comment]
the same issue happens when I use Link from next and pass routes using `as` and `href`.

**Comment by avetisk** [comment]
Same here, when I use a pattern, while everything goes properly and rendering is done correctly, I still get as 404 status on the rendered page.

**Comment by waskito** [comment]
> My routes are like this:
> 
> ```
> // routes.js
> module.exports = routes()
>     .add("about")
>     .add("city", "city/:city", "city")
> ```
> My server is running on port `5010` and dev server is running on `5000`.
> 
> When I visit a route /city/city1 and refresh then it renders the respective city page on the server but on the client(i.e port `5000`) it throws 404 page.
> 
> For the client, refresh works only if I visit /city?city=city1

I accidentally fixed this problem by put the `server.use(handler)` after the `server.get(* ....`
```
const handler = routes.getRequestHandler(app)
server.get("*", (req, res) => {
    return handler(req, res)
})
server.use(handler)
```

**Comment by danielcooke1996** [comment]
Related to this I imagine: https://github.com/fridays/next-routes/issues/296
