### ISSUE TITLE
Generate Routes programmatically

### ISSUE THREAD

**Issue by adrianalonso** [fridays/next-routes#291]
Hi!

Are there any way of generate programmaticaly based on route name?

I've noticed that <Link> component don't render a <a href=""></a> element , and for some seo constraints i need render it with href on server side rendering. Currently we have a component wrapped by <a> element and we have to fill href property.

Thanks a lot

**Comment by adrianalonso** [comment]
I have identified than if you put an `<a>` element inside `<Link>` object, next-routes inject href. I think that this is enough for our case, although it could be interesting have service to generate programmatically route href.

**Comment by janbiasi** [comment]
Also came up with this one and I really don't want to write an own function for compiling routes to a simple string ...

**Comment by janbiasi** [comment]
@adrianalonso I found a way which is working after digging the source code and trying things out. It isn't the prettiest syntax - but the more important thing - not documented (cc @fridays @elliottsj) ... Here a short example:

```ts
import routes from 'next-routes';

export default routes()
  .add('test', '/:lang(en|de)/test/:step', 'TestPage');
```

```ts
import routes from './my-routes-above';

routes.findByName('test').toPath({
  lang: 'en',
  step: 'first-step'
});
```
