### ISSUE TITLE
404 using `route/:param` syntax

### ISSUE THREAD

**Issue by dan-cooke** [fridays/next-routes#296]
We recently upgraded to use `next8` our routes file has not changed.

We have added the following route:

`routes.add('test','test/:hello')`

And inside pages/test.js

```
static async getInitialProps({ query }) {
    return { query };
  }

  render() {
    const { query } = this.props;
    return query
  }
```

Navigating to the following route produces a 404
`test/world`

However if we use traditional query params, it works

`test?hello=world`

**Comment by timlee1128** [comment]
`
<Link href="test?hello=word" as="test/word">
  <a>anchor</a>
</Link>
`

**Comment by timlee1128** [comment]
`<Link href="test?hello=word" as="test/word">
  <a>anchor</a>
</Link>`

**Comment by juansalvatore** [comment]
having the same issue

**Comment by radhasatam** [comment]
Same issue here as well.

**Comment by ItsWendell** [comment]
Same issue here with the latest next routes

**Comment by mishanya** [comment]
Same issue after update of next & next-routes

**Comment by danielcooke1996** [comment]
@fridays Any updates on this?

**Comment by benliger1987** [comment]
Seeing this issue only in production (Heroku). Locally works as it should

**Comment by garitma** [comment]
Same issue, break in now v2.

**Comment by abrkn** [comment]
Same issue

**Comment by jfbaraky** [comment]
I was having the same problem here and I found it's because the route declaration is environment aware. 

I'm using the `dotenv` package to define my environment variables and was calling the `dotenv.config()` after the import of the routes file, making the `NODE_ENV` undefined on the routes declaration.

Using `NODE_ENV=production node server.js` also make it work as expected.

**Comment by Joci933** [comment]
Same issue here. `param/param2?id=2` work well with `Router.push` and `<Link/>` component, but it's throw 404 not found on browser refresh. (f5)
