### ISSUE TITLE
 Handling folders with next-routes

### ISSUE THREAD

**Issue by Saikilito** [fridays/next-routes#297]
Hello

I usually use a folder called "src" for all the components, containers and pages of react.js, in this case I set up next.js so that it does not look for the folder "pages" in the root but in the "src" folder, this work very well when i use the script "dev":"next ./src". 

Now when I want to use next-routes this seems to leave to work, is there any way to fix it? I already tried the script "dev":"node./src/server.js" and it did not work.

first of all, Thanks

**Comment by Pitasi** [comment]
In my package.json I have something like 

```json
{
  "scripts": {
    "dev": "cd src && node server.js"
  }
}
```
