### ISSUE TITLE
Full page load when clicking on a <Link> 

### ISSUE THREAD

**Issue by nikolovjd** [fridays/next-routes#302]
Why is clicking on a link causing a full page load?

My routes.js
```javascript
const routes = require('next-routes');

module.exports = routes()
  .add('register')
  .add('index', '/')
  .add('confirm-email', '/confirm-email/:token');
```

server.js
```javascript

app.prepare().then(() => {
  const server = express();

  server.use(cookieParser());

  // SOME POST ROUTES ADDED HERE
  });

  server.use(handler);
  server.listen(4000);
});
```

I'm using the Link component imported from routes.js, like this:
```jsx
     <Link route="index">
         <a>Index</a>
     </Link>
```

**Comment by alanhr** [comment]
Hello @nikolovjd, 
Which the link do you using `next/Link` or `next-routes/link` ?

**Comment by jaabiri** [comment]
You can fix this by removing
  ```.add('index', '/')```
next-router will render ( full page load ) the page when the name and the path don't match.

.add('bb', '/aaa');   //   full page load

**Comment by nikolovjd** [comment]
@alanhr I'm using next-routes/link

@jaabiri This doesn't explain why also register does full page load.

**Comment by alanhr** [comment]
@nikolovjd  normally I use this way ` .add({ name: 'home', pattern: '/', page: 'home' })`

**Comment by komailf67** [comment]
> Why is clicking on a link causing a full page load?
> 
> My routes.js
> 
> ```js
> const routes = require('next-routes');
> 
> module.exports = routes()
>   .add('register')
>   .add('index', '/')
>   .add('confirm-email', '/confirm-email/:token');
> ```
> 
> server.js
> 
> ```js
> app.prepare().then(() => {
>   const server = express();
> 
>   server.use(cookieParser());
> 
>   // SOME POST ROUTES ADDED HERE
>   });
> 
>   server.use(handler);
>   server.listen(4000);
> });
> ```
> 
> I'm using the Link component imported from routes.js, like this:
> 
> ```js-jsx
>      <Link route="index">
>          <a>Index</a>
>      </Link>
> ```

same problem!

**Comment by duveborg** [comment]
Did you find a solution for this?
