### ISSUE TITLE
Negative regex matches

### ISSUE THREAD

**Issue by stevenmusumeche** [fridays/next-routes#309]
I'm trying to match a catch-all route which matches all paths except those that end with `.ico`.  The regular expression for this is straightforward:

```.add(`/:path(?!.*ico)`, 'static-content')```

however, I get the following error, because the exclamation point is being escaped. 

` SyntaxError: Invalid regular expression: /^\/(?\!.*ico)(?:\/)?$/: Invalid group`

**Comment by dima-kov-prepler** [comment]
@stevenmusumeche, hey is there any workaround?
