### ISSUE TITLE
how to use next-routes with the NextJS api routes

### ISSUE THREAD

**Issue by dohomi** [fridays/next-routes#323]
Hello,

I would like to know how to setup for example a sitemap.xml route. I am using the NextJS api/sitemap.ts folder in the hope that this will work out of the box but it seems only React routes are allowed.

Is there an example available how to set this up?

**Comment by Bundas** [comment]
Did you find out how to do it? I am having same problem

**Comment by andrekorolev** [comment]
I've faced with the same problem. Do you have any updates here?

**Comment by dohomi** [comment]
I'm using newest version of NextJS 9.3.x which made the use of next-routes not necessary any more: 
```js
 experimental: {
      async rewrites () {
        return [
          {source: '/sitemap.xml', destination: '/api/sitemap'}
        ]
      }
    },
```

**Comment by jhenriquevissotto** [comment]
I have the same problme.
