### ISSUE TITLE
Nextjs v9 - Parameter 'url' must be a string, not undefined

### ISSUE THREAD

**Issue by arminops** [fridays/next-routes#332]
Dudes, I recently updated my nextjs project to 9.2. `next-routes` version is "^1.4.2". I got this error after update. 
`Uncaught TypeError: Parameter 'url' must be a string, not undefined`. 
It happens when i pass some params to the `Link`.

Can i handle this with my custom Link component? and if yes how to create it?

routes.js
```
const routes = require('next-routes');
module.exports = routes()
    .add('homepage', '/', 'index')
    .add('dashboard', '/dashboard', 'dashboard/index')
    .add('profile_navigation', '/dashboard/profile/navigation', 'dashboard/profile/navigation')
    .add('profile_userInfo', '/dashboard/profile/user-information', 'dashboard/profile/userInfo')
    .add('profile_education', '/dashboard/profile/education', 'dashboard/profile/education')
    .add('eqResultTests', '/assessment/eq/result', 'exams/eq/eqResultTest' )
    .add('ResultsExams', '/results-exams', 'exams/resultsExams')
```

**Comment by meabed** [comment]
I have just forked the repo and updated it to latest versions with the correct types, all test are passing 🟢 👍 
https://github.com/meabed/next-routes-extended
https://www.npmjs.com/package/next-routes-extended
