### ISSUE TITLE
Is this library alive?

### ISSUE THREAD

**Issue by GMaiolo** [fridays/next-routes#334]
There have been a lot of changes in NextJS router and other core functionalities and it seems that this library hasn't been updated for more than **2 years** now

**Comment by irhamputra** [comment]
@GMaiolo i think so but luckily this lib is still compatible with next v9. I've been using this start from last week it is still working right now. idk after next.js team release new major version

**Comment by joaogarin** [comment]
Not completely https://github.com/fridays/next-routes/issues/329

**Comment by osphost** [comment]
Considering the number of people that probably use this library, the maintainer/owner of next-routes should update the README informing people that its not longer being actively maintained.

I will be removing it from my project now.

**Comment by msreekm** [comment]
Assuming that this library is kind of abandoned at this point, Is there an alternate library for  routing with next.js, if someone do not want to use file based routing ?

**Comment by Judahmeek** [comment]
Anyone got a guide for removing this library?

I took over a project using this library & my attempt to remove it resulted in `Cannot GET` errors from all routes. You'd think I had deleted the `pages` directory or something.

**Comment by joaogarin** [comment]
Unfortunately the problem is that next doesnt have certain features in order to really remove the library. Custom routes in nextjs will help (and maybe enough for certain use cases) but there is no fully dynamic route solution like this library provides (if you have for example routes comming from a CMS).

**Comment by kenberkeley** [comment]
https://github.com/fridays/next-routes/issues/244#issuecomment-564069911

**Comment by GMaiolo** [comment]
@kenberkeley still radio silence though, and no updates to the library since June 29, 2018

**Comment by GMaiolo** [comment]
@kenberkeley still radio silence though, and no updates to the library since June 29, 2018

Ping @Timer!

**Comment by msreekm** [comment]
From what I have seen so far , the next,js project priorities are set for what is required for vercel platform and not necessarily based on the needs of the community. in this case ,this may be a low priority for vercel.

**Comment by andreasblueher** [comment]
The last commit to github! by the owner was in may 2019. It seems he has not abandoned this library, but rather github in general. What about some contributers here? Someone who would take over? is that even possible?

**Comment by ostenning** [comment]
This library shouldn’t be used anymore. Use the inbuilt nextjs routing

**Comment by andreasblueher** [comment]
Thanks for pointing that out @ostenning

**Comment by msreekm** [comment]
I have already started the migration process to  next routing.

**Comment by meabed** [comment]
I have just forked the repo and updated it to latest versions with the correct types, all test are passing 🟢 👍 
https://github.com/meabed/next-routes-extended
https://www.npmjs.com/package/next-routes-extended

**Comment by albertvolkman** [comment]
@meabed 

I think you have an issue here- https://github.com/meabed/next-routes-extended/blob/master/package.json#L39

When trying to install your package, I get an error `Invalid tag name "=>15.4.2": Tags may not have any characters that encodeURIComponent encodes.`

**Comment by meabed** [comment]
> @meabed 
> 
> 
> 
> I think you have an issue here- https://github.com/meabed/next-routes-extended/blob/master/package.json#L39
> 
> 
> 
> When trying to install your package, I get an error `Invalid tag name "=>15.4.2": Tags may not have any characters that encodeURIComponent encodes.`

Oops 🙊 you are right, I'll fix this right away and release it.
I'm also planning to add more examples, we are using this routes extensively in a lot of different use cases and I think it will be helpful to share them as well.

**Comment by meabed** [comment]
@albertvolkman is fixed and pushed!
I am adding an example folder with different use-cases later today!

**Comment by cvolant** [comment]
@meabed thank you to take over.
Do you plan to make it compatible with Next built-in i18n routing?

**Comment by meabed** [comment]
> @meabed thank you to take over.
> Do you plan to make it compatible with Next built-in i18n routing?

Yes - absolutely - I am adding and example code-sanebox with all use cases, i use it already multi-lingual and works well! 
I will share different complete working solution with codesanbox, if you have something specific let me know.
Thank you!

**Comment by cvolant** [comment]
Great!
And do you think it will support getStaticProps? Like:
```
MyPage.getStaticProps(({ locale }) => {
  [...]
})
```

**Comment by GMaiolo** [comment]
Could we move the convo about the fork to the fork? Seems proper
