### ISSUE TITLE
Refresh results in 404 page not found

### ISSUE THREAD

**Issue by rachit2501** [fridays/next-routes#335]
This is my routes.js:
```
const routes = require("next-routes")();

routes
  .add("/campaigns/new", "/campaign/new")
  .add("/campaigns/:address", "/campaign/show");

module.exports = routes;
```

When I click on the button which redirects to something like :
http://localhost:3000/campaigns/0x529555e950E9e2924332C35bB3e79f4B9Ad49881,
The show component renders fine. But on refreshing the page I get a 404 not found.

Server.js:
```
const { createServer } = require("http");
const next = require("next");

const app = next({
  dev: process.env.NODE_ENV != "production"
});

const routes = require("./routes");
const handler = routes.getRequestHandler(app);

app.prepare().then(() => {
  createServer(handler).listen(3000, err => {
    if (err) throw err;
    console.log("Ready on localhost:3000");
  });
  ``;
});

```

**Comment by Yaxian** [comment]
Try to add static method `getInitialProps`  to the  `Component`  export from  page `/campaign/show`  . For example: 
```
function CampaignShowPage () {}

CampaignShowPage.getInitialProps = () => {
     return {}
}

export default CampaignShowPage
```

**Comment by rachit2501** [comment]
I am already using getIntiiaProps in /campaign/show.

**Comment by jaoord** [comment]
Did you already find a solution? I had the same problem, visiting the link works fine but refreshing returns a 404.
What seems to work for me is removing the / in front of the page, so in your case that would be

````js
routes
  .add("campaigns/new", "/campaign/new")
  .add("campaigns/:address", "/campaign/show");
````

**Comment by rachit2501** [comment]
Oh Thanks for that. It worked for me too.
