### ISSUE TITLE
Compatibility with getStaticPaths

### ISSUE THREAD

**Issue by dhacquebord** [fridays/next-routes#337]
Hi,

Did anyone succeed in using this module in combination with getStaticPaths?

It appears that getStaticPaths needs the dynamic routes to be placed in a filename like `pages/users/[id].js` but i can't find a way to make this module work with these filenames.

What i'm trying to achieve is changing `/users/:id` to `/gebruikers/:id` and statically render them using getStaticProps and getStaticPaths.

**Comment by DonovanCharpin** [comment]
I have the same issue, did you find a workaround?
