### ISSUE TITLE
slugs are not working with dynamic routes after upgrading to next 9.5

### ISSUE THREAD

**Issue by sarang-naico** [fridays/next-routes#340]
After upgrading the next js to the version 9.5 the slugs are not working in dynamic pages
Router.pushRoute('blog', {slug: 'hello-world'})
 @disintegrator @petertulala @Timer @tpreusse @trotzig

**Comment by arminops** [comment]
for me 
After updating 'next js' version. It's not working at all with ssr

**Comment by meabed** [comment]
I have just forked the repo and updated it to latest versions with the correct types, all test are passing 🟢 👍 
https://github.com/meabed/next-routes-extended
https://www.npmjs.com/package/next-routes-extended
