### ISSUE TITLE
Next 10

### ISSUE THREAD

**Issue by mkasper1-godaddy** [fridays/next-routes#345]
Just upgraded to NextJs 10 and the pushRoute no longer does client side routing, im always getting a page reload. Are others having this same issue?

**Comment by Bodda1** [comment]
Yes, I have the exact same issue but not all the time; some times it does work but most of the times it does a full page reload

**Comment by ScriptedAlchemy** [comment]
Does your js ever silently crash? On my side, when using query strings and wildcards, my menu stops working (no state changes) and the app seems to silently fail. Only on a page that's client side handled
