### ISSUE TITLE
Migrating from next-routes to built-in Next.js routing?

### ISSUE THREAD

**Issue by keithpickering** [fridays/next-routes#347]
We are trying to update React/Next in our project and updating any necessary dependencies along the way. Most of these are straightforward, but for routing we're not using the new filesystem-based implementation at all. We wrap our <App /> in a `BrowserRouter` from `react-router-dom`, and we use next-routes to traverse them within at least 35 component files. Since this library is no longer maintained, can anyone recommend a guide for migrating to the new system so I can avoid any known pitfalls?

**Comment by Fonger** [comment]
We face the same pain too. I think first we shoud mark this repo deprecated on npm to prevent others from using it.
