### ISSUE TITLE
change value of this.props.url.pathname

### ISSUE THREAD

**Issue by iamdevonbutler** [fridays/next-routes#35]
I set up my index route like this:
```javascript
routes.add('index', '/');
```
this.props.url is injected into my pages w/ a "pathname" attribute...among others. For this particular route, it's pathname value is "/index". I don't see how this value is useful. Shouldn't the pathname be the pattern param. We could also inject the route name param as a property on "url". 

On another page I use this route:
```javascript
routes.add('contactGeneral', '/contact/general', 'contact-general');
```
And this.props.url.pathname === '/contact-general'. Just doesn't make a lot a sense.

**Comment by fridays** [comment]
Pathname and other properties are provided by Next.js, please check the docs [here](https://github.com/zeit/next.js#with-link). It refers to the current page module.
