### ISSUE TITLE
Parameters vs Query

### ISSUE THREAD

**Issue by nishtacular** [fridays/next-routes#36]
Hey guys, I'm trying to resolve an issue and was hoping for some help. When navigating to a sub route from the client I am getting the `sku` field as query string, but I need it as a parameter. It works as a parameter on server load but not client.
**Example**
```
<Link route='product' params={{sku:product.sku}}><a>Product 1</a></Link>
<Link route='product' params={{sku:product.sku}}><a>Product 2</a></Link>
```
Now if I load this url `/product/123` directly it works and loads the correct page. However, if I am on another page and click on the links above the url read `/product?sku=123`. I need both links to the the former. How can I get this fixed. Appreciate any pointers.

**Comment by nishtacular** [comment]
Further testing shows that if I have `/products` and `/products/:sku` listed in my `routes.js` file it cause this issue, basically forces it into a query string. However, if I were to have only the `/products/:sku` option in my routes `sku` is passed as a parameter.

** Example 1**
```
// routes.js
const nextRoutes = require('next-routes')
const routes = module.exports = nextRoutes()

routes.add('test', '/test')
routes.add('test', '/test/:sku') // the sku passed as a query string - http://acme.com/products?sku=123
```
** Example 2**
```
// routes.js
const nextRoutes = require('next-routes')
const routes = module.exports = nextRoutes()

routes.add('test', '/test/:sku') // the sku passed as a parameter - http://acme.com/products/123
```

**Comment by nishtacular** [comment]
Sorry, guys I figured it out. Must be the lack of sleep playing tricks 😳

**Comment by seansamuelson** [comment]
@nishtacular - having the same issue but without the sleep excuse, do you mind sharing what your solution was?

**Comment by supra28** [comment]
@nishtacular What was the problem here ?

**Comment by nishtacular** [comment]
@supra28 Not sure if you're still after an answer but from memory i wasn't including the sku in route definition. See example below
```
routes.add('product', '/product'); // the WRONG way
--
routes.add('product', '/product/:sku?'); 
```
