### ISSUE TITLE
Every file in pages is still a route, how to disable them and only allow routes defined through next-routes to exist?

### ISSUE THREAD

**Issue by exogenesys** [fridays/next-routes#44]
I have defined the routes, all of them with parameters. But still, I can access them without parameters. Next-routes is not overriding the routes defined by next. How do I fix this?

Thanks a lot!

**Comment by fridays** [comment]
If you define the routes without parameters, they will override the original file based routes.

It should soon be possible to disable file based routes completely: https://github.com/zeit/next.js/pull/914

**Comment by exogenesys** [comment]
Cool, thanks a lot. :)

**Comment by goldensunliu** [comment]
following the merge closely. and will help when it is in a stable release of next.js
