### ISSUE TITLE
Object.assign not polyfilled

### ISSUE THREAD

**Issue by jaydenseric** [fridays/next-routes#53]
This package breaks in IE 11 due to it's unpolyfilled use of `Object.assign`.

It is risky to rely on Next.js to apply a global polyfill, because its not guaranteed - in v3 latest it is not present:

<img width="435" alt="screen shot 2017-06-20 at 11 05 28 pm" src="https://user-images.githubusercontent.com/1754873/27334673-66124320-560d-11e7-830f-ed4726ff8cd2.png">

This issue can be resolved by refactoring all usage of `Object.assign` to spread operator syntax. It's more elegant that way anyway.

**Comment by fridays** [comment]
This is now fixed with new babel presets.
