### ISSUE TITLE
v3.0.0 support of next.js

### ISSUE THREAD

**Issue by oliviertassinari** [fridays/next-routes#57]
Thanks for this great project.
I have been trying out the latest release of `next.js`: `3.0.0-beta16`.
I have noticed that the Link component of `next-routes` wasn't able to change the current route.
Is this library supporting that version of next.js yet?

**Comment by HaNdTriX** [comment]
@oliviertassinari thanks for your feedback!
I am using next-routes with next@beta-3 and it works fine.
Could you provide some more infos?

**Test Case:**
```bash
$ curl https://codeload.github.com/zeit/next.js/tar.gz/master | tar -xz --strip=2 next.js-master/examples/using-router
$ cd using-router
$ yarn install && yarn upgrade next@beta && yarn dev 
```

**Comment by oliviertassinari** [comment]
That's good to know, I will dig more into the issue then.
