### ISSUE TITLE
Unname routes update breaking change

### ISSUE THREAD

**Issue by smiled0g** [fridays/next-routes#61]
Hi,

We've been using name routes which name starts with "/" for a while. For example, we had a route with name "/teacher/assignment". It was working fine, until the 1.0.30 update, which mistakes such routes to be unnamed routes.

It's not a big deal. We just need to change all the named routes so that they don't start with "/". Still, it would be nice if the developer is more mindful about breaking changes such as this.

Regards

**Comment by fridays** [comment]
Sorry for that! 🙏 

In the future it will follow proper semantic versioning.
