### ISSUE TITLE
HMR not working when integrating next-routes

### ISSUE THREAD

**Issue by adrianha** [fridays/next-routes#64]
Hi,
I'm facing an issue that HMR is not working when using next-routes. It will do full reload instead.
I already followed the example given on the readme.

Here's my implementation:

**routes.js**
```
const nextRoutes = require('next-routes');
const routes = module.exports = nextRoutes();

const localeRegExp = '(/id|/en)?';
routes.add('index', localeRegExp);
routes.add('search', `${localeRegExp}/search/:urlName`);
```

**server.js**
```
const routes = require('./routes');
const handler = routes.getRequestHandler(app);
const server = express();

app.prepare()
.then(() => {
  server
  .use(handler)
  .listen(3000, function (err) {
    console.log('err', err);
  })
})
```

Any idea about this?

**Comment by fridays** [comment]
Try to move the slashes out of the regex:
```javascript
const localeRegExp = ':locale(id|en)?';
routes.add('index', `/${localeRegExp}`);
routes.add('search', `/${localeRegExp}/search/:urlName`);
```

**Comment by adrianha** [comment]
Hi @fridays , the issue is still occurred..
When i changed content on pages/index.js, it will do full-reload

**Comment by fridays** [comment]
Please provide a sample repo @adrianha

**Comment by adrianha** [comment]
Heres the sample repo: https://github.com/adrianha/next-routes-demo
If i made changes on pages/index, it will do full reload.. @fridays

**Comment by fridays** [comment]
Thanks for reporting this, please update to version 1.0.39

**Comment by adrianha** [comment]
Great! Thank you very much @fridays !
