### ISSUE TITLE
Server-rendering does not match client

### ISSUE THREAD

**Issue by runemadsen** [fridays/next-routes#67]
After switching to React routes, I'm getting the following error in the console:

```
warning.js?c5303db:36 Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) r" id="react-select-2--value" data-react
 (server) r" id="react-select-10--value" data-reac
```

This is the page that is rendering: https://github.com/runemadsen/artefact-next/blob/updateWorks/next/pages/work.js

This is my server setup: https://github.com/runemadsen/artefact-next/blob/updateWorks/next/server.js

Is this a problem with my config of next-routes?

**Comment by fridays** [comment]
It looks more like a problem with [react-select](https://github.com/JedWatson/react-select/issues/1726) and server-rendering. You can try to only render that form component after `componentDidMount` then it will only render on the client.

**Comment by runemadsen** [comment]
Got it. Thanks for the quick reply!

**Comment by heldervilela** [comment]
My solution is only render the component in client-side using [react-no-ssr](https://www.npmjs.com/package/react-no-ssr)
