### ISSUE TITLE
HMR issue on global stylesheet

### ISSUE THREAD

**Issue by adrianha** [fridays/next-routes#69]
Hi @fridays ,
currently im facing issue on the HMR again when integrating global stylesheets to the project.
Here's the repo to reproduce it: `https://github.com/adrianha/next-routes-demo`
Thanks!

**Comment by fridays** [comment]
Hi @adrianha I think it's not related to `next-routes`, it does a full reload on css changes even when run without the custom server

**Comment by adrianha** [comment]
Ah my bad, yes its not related to `next-routes`. There was misplaced on the code. Sorry for this @fridays .
