### ISSUE TITLE
Enhancements

### ISSUE THREAD

**Issue by chaffeqa** [fridays/next-routes#71]
We ended up having to do a quick cut over from our react-router + redux massive SPA to next.js.  We used this lib to help convert the react-router style routes to next.js.

However we ended up "forking" (shoving into our repo) this lib to allow for:

* preload support
* dev preload
* redirect support

You can see our implementation [here](https://github.com/chaffeqa/nextjs-app)

Our `next-routes` implementation is [here](https://github.com/chaffeqa/nextjs-app/blob/master/routes/NextRoutes.js) in the repo

Please feel free to reach out on this issue with questions, I hope to have more time to write a blog post on this / make some pull requests here, but I dont know if I will have the time for that as of yet

Thanks for such a great OS project!

**Comment by fridays** [comment]
Thanks for sharing!

We support `<Link prefetch>` and there is `Router.prefetchRoute()` but in development mode Next.js now uses [on demand entries](https://github.com/zeit/next.js/pull/1111) for performance improvements.

The latest version supports `<Link to='/any/path'>` like in react-router

A redirect feature would be great, I think many people would like this. Any PR welcome!
