### ISSUE TITLE
nextjs HMR always reload index page

### ISSUE THREAD

**Issue by acanimal** [fridays/next-routes#73]
From what I have experienced, since version 1.0.40 it seems nextjs always reloads the index page.

**Comment by fridays** [comment]
Could you share a sample to reproduce the issue?

**Comment by acanimal** [comment]
In development the nextjs app checks for code updates invoking `/_next/on-demand-entries-ping?page=/` which results in a message like `Client pings, but there's no entry for page:` on server side and produces the whole app will be loaded.

I think it has something to do with this https://github.com/fridays/next-routes/blob/master/src/index.js#L125

**Comment by fridays** [comment]
The URL is correct actually (try without next-routes). I can't see any issues, please share some code to reproduce it.

**Comment by acanimal** [comment]
Maybe is due this fix you done in last release of nextjs: https://github.com/zeit/next.js/pull/2505
We have a previous version. I'll try to update and check.

**Comment by fridays** [comment]
Is it solved?
