### ISSUE TITLE
Error: Route "..." already exists

### ISSUE THREAD

**Issue by lsdafjklsd** [fridays/next-routes#74]
This technique had been working, installed the latest npm version and it's broken.

```javascript
routes.add('entity', '/entity/:actor_id/:tab')
routes.add('entity', '/entity/:actor_id')
```

/node_modules/next-routes/dist/index.js:89
        throw new Error('Route "' + name + '" already exists');
        ^
Error: Route "entity" already exists

**Comment by fridays** [comment]
Sorry! A route name must be unique, but you can do this in one line:
```javascript
routes.add('entity', '/entity/:actor_id/:tab?') // <- note "?"
```

**Comment by lsdafjklsd** [comment]
Oh nice, thank you, missed that syntax.
