### ISSUE TITLE
Navigate using path and pass params via params props

### ISSUE THREAD

**Issue by adrianha** [fridays/next-routes#75]
Hi @fridays ,
Is it possible to navigate like this?
`Router.pushRoute('/search', { id: 1, name: 'abc' });`
It looks like that params is not passed when given the path in the first parameter.
Heres the example repo: [Example](https://github.com/adrianha/next-routes-demo)

**Comment by fridays** [comment]
Hi @adrianha you can either use route name & params or a url to resolve:
```javascript
// routes.js
routes.add('search', '/search/:id/:name')

// Route name and params
Router.pushRoute('search', {id: 1, name: 'abc', more: 'things'})

// Or resolve url
Router.pushRoute('/search/1/abc?more=things')
```

**Comment by adrianha** [comment]
```
// Or resolve url
Router.pushRoute('/search/1/abc?more=things')
```
Hello @fridays ,
If i resolved the url using that method, i found that the third options on pushRoute wont take an effect.
Example:
```
Router.pushRoute('/search/1/abc?more=things', {}, { shallow: true }); => getInitialProps is called
Router.pushRoute('search', { id: 1, name: 'abc', more: 'things' }, { shallow: true }); => getInitialProps is not called as expected 
```
Is there any way to pass the options when i resolve the route using url?
Thanks

**Comment by fridays** [comment]
Pass options as the second argument. When resolving by URL, there is no params argument. We need to make this clear in the readme.
