### ISSUE TITLE
Should we avoid mutating the next/router?

### ISSUE THREAD

**Issue by oliviertassinari** [fridays/next-routes#77]
I have ran into an issue where `next-routes` is called twice.
It's a mistake on my end, I have multiples routes to handle different subdomains.
I'm supposed to always import the routes of a the current subdomain.

However, a slight import mistake has wide side effect. I think that we have an opportunity to reduce the impact of such possible mistake.
What's the root cause? I have finally found that [this modules is mutating `next/router`](https://github.com/fridays/next-routes/blob/c916690c71c7d2ca5aa1163edf43b7d396050b77/src/index.js#L110).

What do you think of stopping doing such? I mean returning a new object reference.

Also, I'm gonna add a safe defensive code on my end to throw when the `next-routes` is called a second time.

**Comment by oliviertassinari** [comment]
For anyone interested, here his my self defensive code:

**www/routes.js**
```jsx
import NextRouter from 'next/router'
import nextRoutes from 'next-routes'

if (process.browser && NextRouter.pushRoute) {
  throw new Error('Call twice!')
}

const routes = nextRoutes()
routes.add('www/home', '/')
// ...

export const Router = routes.Router
export const Link = routes.Link

export default routes

```

**Comment by fridays** [comment]
Thanks, I agree it would be better to not modify it. It was it's own object before, but there was a problem with Router events: https://github.com/fridays/next-routes/pull/18 If you could send a PR that solves this would be really cool.

**Comment by oliviertassinari** [comment]
I'm fine with the checks I have added in userland, I need them independently of this issue. It's not a priority for me. Feel free to close the issue.
