### ISSUE TITLE
Load different Pages

### ISSUE THREAD

**Issue by supra28** [fridays/next-routes#81]
How to load different pages for routes like 
`xyz.com/locations
`and
` xyz.com/locations/4
`
How do I name my routes and use the link component to achieve this?

**Comment by supra28** [comment]
I've added my routes like 
```
routes.add("locations", "/locations", "locations")
routes.add("locationPage", "/locations/:id", "location-page")
```
but when I click this link component 
```
<Link route="locations/54">
          <a>woop</a>
 </Link>
```
It shows a 404 page and the reloads to the correct page :/

**Comment by netoho** [comment]
@supra28 Did you find a solution?

I'am having the exact same problem, maybe it is due to mis configuration https://github.com/fridays/next-routes/issues/114
