### ISSUE TITLE
How to update window location on Link click?

### ISSUE THREAD

**Issue by foxhound87** [fridays/next-routes#9]
It seems that clicking on the Link component, the window location in the browser address bar is not updated. 

What's the best approach to make it working without break SSR? Is this feature supported by the next-routes package?

Thank You.

**Comment by fridays** [comment]
Hey, it should work as you expect, clicking the link should update the address bar. The Link component only generates the URL and passes the right arguments to the original next.js Link component. Can you show some code where the problem happens?

**Comment by foxhound87** [comment]
I made it working. 
I was using the router names wrongly.
