### ISSUE TITLE
typescript typings

### ISSUE THREAD

**Issue by BjornMelgaard** [fridays/next-routes#92]
```
 ✘  ~/projects/react-hipstaplate   master ●✚  ya @types/next-routes
yarn add v0.28.4
[1/5] Validating package.json...
[2/5] Resolving packages...
error Couldn't find package "@types/next-routes" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

```

**Comment by corydeppen** [comment]
I don't know if anyone else has worked on trying to create the TS definitions for this lib yet, but I ran into a wall when trying to expose the `Link` class as a named export. I'm thinking it may have to do with the API design as mentioned in #63. It may be best to wait until those changes are made before continuing with these definitions.

Is there any opposition to maintaining the TS definitions in this repo, or is the preference to keep them in the DefinitelyTyped repo?

**Comment by majelbstoat** [comment]
Yeah, I spent a good few hours trying to make this work and gave up in the same place :/

**Comment by disintegrator** [comment]
I just opened #153 to get typings included in this project :)

**Comment by fridays** [comment]
Thanks @disintegrator
