### ISSUE TITLE
how to add get Parameters?

### ISSUE THREAD

**Issue by huvber** [fridays/next-routes#93]
Hi, 
I wanted to say you thanks for you work, it's great. 
I'm using your `Link` component but I need to add also getParams like '?key=value&another=value'

It's possible to set the `query` of the href of the Next's Link component. ?

something like this: 
```
<Link route="my-route" params={{slug: 'my-article'}} query={{key: 'value', another: 'value'}}>press me</Link>
```

**Comment by fridays** [comment]
Hey, you can do that by passing the extra parameters with the params prop. All params that are not defined in the route pattern will be added as querystring.

**Comment by signalwerk** [comment]
The same is not true for `Router.pushRoute('/home', {key: 'value', another: 'value'})` right? Here I have to encode by hand if I have extra params: `Router.pushRoute('/home?key=value&another=value')`
