### ISSUE TITLE
In prod build, all pages (except /) return 404 when server rendered

### ISSUE THREAD

**Issue by nickrobillard** [fridays/next-routes#98]
I originally found this issue and posted about it here https://github.com/zeit/next.js/pull/2613. Since then, I have found that it is a much more general bug in next-routes. When I test a prod build (`next build` and `next start`), server generated sub-pages return 404. This is reproducible with the next-routes example in the next repo - https://github.com/zeit/next.js/tree/master/examples/with-next-routes.

**Steps to reproduce:**

1. Follow installation instructions (https://github.com/zeit/next.js/tree/master/examples/with-next-routes)
2. Run commands `next build` followed by `next start`
3. Navigate to the first link `Blog: Hello world`
4. Refresh page and observe 404

I'm assuming this was working at some point. Maybe this was introduced in Next.js v3?

<img width="689" alt="screen shot 2017-09-12 at 8 49 30 pm" src="https://user-images.githubusercontent.com/135516/30358876-14b6ba2a-97fc-11e7-9ee7-42ee0bc9e15c.png">

**Comment by nickrobillard** [comment]
Ok this is my bad. I should have been using `npm run start` or `yarn start` to start the prod server. Issue resolved.

**Comment by bntzio** [comment]
@nickrobillard How did you solve it? I'm facing the same error on production only, 404 for sub-pages as well if I enter directly, but not if using `<Link>`.

**Comment by nickrobillard** [comment]
In Step 2, replace `npm start` with `npm run start` or `yarn start`. `npm start` starts the server with default  next config, which is wrong because this example uses a custom server. Credit goes to @grokling on slack for catching this.

**Comment by bntzio** [comment]
Oh got it!! Do we need to run our own server (`node server.js`) instead of the next.js one (`next start`) right?

It's working now 😄 thanks!

**Comment by nickrobillard** [comment]
Yes, you can see this in the example's `package.json`. The `build` script runs `NODE_ENV=production node server.js`.

**Comment by andrewmartin** [comment]
Oh man, thank you so much. Was wrangling with this one for a minute and driving myself nuts...Realized I had a wonky `ecosystem.config.js` using `npm run start` instead of `yarn start`
